### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by pengyanbing84** [jin10086/browser-environment-test#2]
![image](https://user-images.githubusercontent.com/34937085/82748287-3325d880-9dd3-11ea-814a-4a22ace46ed1.png)

**Comment by pengyanbing84** [comment]
![snipaste20200524_152941](https://user-images.githubusercontent.com/34937085/82748311-67999480-9dd3-11ea-8db2-b85b3b439139.png)

**Comment by jin10086** [comment]
你需要下载项目的index.html

**Comment by pengyanbing84** [comment]
> 你需要下载项目的index.html
只能在谷歌打开index.html?
我在火狐浏览器打开错误
![image](https://user-images.githubusercontent.com/34937085/82750524-4771d180-9de3-11ea-9f4e-8074202d6166.png)

**Comment by jin10086** [comment]
`python -m http.server` 是启动一个web server

你在项目目录下运行这个就可以 http://localhost/index.html 打开了，你那是直接打开文件

**Comment by pengyanbing84** [comment]
> `python -m http.server` 是启动一个Web服务器
> 
> 你在项目目录下运行这个就可以[http：//localhost/index.html](http://localhost/index.html)打开了，你那是直接打开文件

就是遍历window对象,把属性全部保存成json文件

请问在selenium中怎么使用这个json文件，添加到selenium中？
在selenium添加所有的浏览器的属性，保存在json文件中的都是浏览器的属性吧
